version: 1.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Debug
  
build:
  project: WPF_SL_Combined_Toolkit\WPF_SL_Combined_Toolkit.sln

after_build:
  - ps: .\nuget\pack.ps1

test: off

artifacts:
  - path: WPF_SL_Combined_Toolkit\WPF_SL_Combined_Toolkit\bin\Debug\WPF\WPF_SL_Combined_Toolkit.dll
    name: WPF_SL_Combined_Toolkit.dll
  - path: WPF_SL_Combined_Toolkit\WPF_SL_Combined_Toolkit\bin\Debug\WPF\WPF_SL_Combined_Toolkit.pdb
    name: WPF_SL_Combined_Toolkit.pdb
  
#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: OrhpK2cLXXcoWW+hU6xAv3eeKIbATEFbenteoFsi9EfM1yyDof6ZuNKAsA3Vy6vb
  artifact: **\*.nupkg
  
  
  