version: 2.0.{build}

branches:
  only:
    - master

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Debug

image: Visual Studio 2019

before_build:
  - nuget restore WPF_SL_Combined_Toolkit\WPF_SL_Combined_Toolkit.sln
  
build:
  project: WPF_SL_Combined_Toolkit\WPF_SL_Combined_Toolkit.sln

test: off

artifacts:
  - path: '**\DotNetProjects.WPF_SL_Combined_Toolkit*.nupkg'
  
#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: bdhemLvYgto+o1hjkJ9OhVRANxW6+U9RTGQre/KqyV3mFWmN5BQA6ZpMoHbjsaJW
  artifact: /.*\.nupkg/
  
  
  